#!/bin/bash

#Email Data from Parameters
smtpFrom=$1
smtpServer=$2
smtpUser=$3
smtpPass=$4
subject=$5

#Format File for Input and verify Input
awk -F";" ' NR>=3 {if(($2 ~ /^[a-zA-Z]+$/)&&
		      ($3 ~ /^[a-zA-Z]+$/)&&
		      ($4 ~ /@/)&&
	              ($5 ~ /[1-6]/))
			{print $2,$3,$4,$5,$12 > "NotenListeFormatiert.csv";}
		   else
			{print "Fehler in Zeile", NR > "ErrorLog.csv";}}' test2.csv

#Read the messageBody for Email from passed File
messageBody=$(<TestText)

#Read the Formated InputFile and Send the mail
while read Nachname Vorname Email Note PFach
do	
	#Replace the Variables in the body File 
	replaceVorname="${messageBody/<Vorname>/$Vorname}"
	replaceNachname="${replaceVorname/<Nachname>/$Nachname}"
	replaceNote="${replaceNachname/<Note>/$Note}"
	#send the email
	sendEmail -f $smtpFrom -t $Email -u $subject -m $replaceNote -s $smtpServer -xu $smtpUser -xp $smtpPass
done < NotenListeFormatiert.csv 
